import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";
export const metadata = {
  title: "google sign up",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
